<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>AiracGen</Title>
    <Authors>Tim Unger</Authors>
    <Company>Tim Unger</Company>
    <FileVersion>1.4.0</FileVersion>
    <Version>1.4.0</Version>
  </PropertyGroup>

</Project>
